### ISSUE TITLE
Double quote inside code argument

### ISSUE THREAD

**Issue by M0dM** [logstash-plugins/logstash-filter-ruby#11]
Hi,
I tried to use a double quote inside the code "block"
To use it I escaped this double quote. 
Testing configuration with logstash --configtest attribute is OK but an exception occurred when I try to launch logstash.

config file filter block : 

`ruby {
  code => "event['message'] = event['message'].join(\"\n\")"
}`

`SyntaxError: (ruby filter code):1: syntax error, unexpected null
@codeblock = lambda { |event| event['message'] = event['message'].join(\"\n\") }`

**Comment by bobmercer** [comment]
Hi,
I have the same issue... Is it a known limitation ?

**Comment by M0dM** [comment]
I used a tricky workaround finally from my side, 
I used ascii code of \n character to do this.

see : http://stackoverflow.com/questions/308749/whats-the-opposite-of-chr-in-ruby

**Comment by bighanraj** [comment]
use like this  string.split('\"')

**Comment by uschtwill** [comment]
Yes, this! 

I am trying to build some json-strings and thus require single or double quotes. Now, one set of quotes is used for `code => 'code goes here'`, and one set of quotes is used for `string = "string goes here"`. Unfortunately escaping using `/` is not working at all, so this is proving kind of difficult, as there is simply no set of quotes left.

What is currently the best practice to achieve this? Some other escape mechanism? Rolling your own filter? Building the json not by string but by using Ruby arrays and hashes (I tried this, but I think then the `http` output was having trouble dealing with it ?!) ?

I thought I'd better ask, before sinking even more time into this and going in more circles. I can also re-ask this question on the forums, if that's preferred,  I just saw this issue and thought it'd fit here well.

And @bighanraj, what do you mean by that?

**Comment by jsvd** [comment]
due to this an many other limitations, we now have file based ruby scripting: https://www.elastic.co/blog/moving-ruby-code-out-of-logstash-pipeline

If your inline ruby code is complex enough to need double quotes, [consider using file based ruby scripts](https://www.elastic.co/guide/en/logstash/current/plugins-filters-ruby.html#_using_a_ruby_script_file)
