### ISSUE TITLE
Ruby exception occurred: undefined method `getlocal' for LogStash::Timestamp

### ISSUE THREAD

**Issue by svezzoli** [logstash-plugins/logstash-filter-ruby#12]
I need to convert timestamp to local time using logstash 1.5.4. 
The following ruby filter code works just fine in logstash 1.4.2:
ruby { code => "event['@timestamp'] = event['@timestamp'].getlocal }
but now the getlocal method is not working anymore.
The error is:
{:timestamp=>"2015-09-14T10:42:38.380000+0200", :message=>"Ruby exception occurred: undefined method `getlocal' for \"2015-09-14T08:42:38.336Z\":LogStash::Timestamp", :level=>:error, :file=>"logstash/filters/ruby.rb", :line=>"41", :method=>"filter"}

Does anybody have an idea?

**Comment by hp197** [comment]
Yes, @timestamp is of type Logstash::Timestamp (see: https://github.com/elastic/logstash/blob/master/lib/logstash/timestamp.rb)

What would work in your case is:
event['@timestamp'] = LogStash::Timestamp.new( Time.at( event['@timestamp'].to_i() ).getlocal() )

**Comment by svezzoli** [comment]
@hp197 
thanks for the hint.
I will go to test the updated ruby filter code as soon as my environment test will be available again.
 So, for the moment, I don't close this issue.

**Comment by svezzoli** [comment]
The suggested solution works fine.
Thanks.
