### ISSUE TITLE
how to solve this problem by ruby filter

### ISSUE THREAD

**Issue by zhangchao2015** [logstash-plugins/logstash-filter-ruby#13]
My problem is specific as below.
the event message is:
`{"a":[{"aa":"v1"},{"bb":"v2"}]}`
how to add a field ,namely, "a_size" and its value is array a's length. so the output is like below:
`{"a":[{"aa":"v1"},{"bb":"v2"}],"a_size":2 }`

**Comment by untergeek** [comment]
This is not a bug report, but a usage question.  Please close this ticket and ask your question at https://discuss.elastic.co/c/logstash
