### ISSUE TITLE
Lostash ruby filter throws undefined method  `/' for #<Hash:0x7f4ec4d0> {:level=>:error}

### ISSUE THREAD

**Issue by vijay94181** [logstash-plugins/logstash-filter-ruby#18]
here is my logstash conf 
# logstash config

input {
  file {
    path => "/home/vijayverma/sla*.log"
    codec => "json"
    start_position => "beginning"
    type => "sla"
  }
}
filter {
split {
    field => "stats[slaTimes]"
  }
 ruby{
    code=>"event['time']=event['stats[slaTimes[timeElapsedNanos]]']/1000000"
    }
}
output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => "json" }
}

{ "date": "2016-02-12 10:06:35", "level": "INFO1 ", "stats": {"slaTimes":[{"timeElapsedNanos":2803026,"startTime":"2016-02-12 10:06:35.519 UTC","id":"com.ebee.app.web.rest.MetaGridResource.getGridQueryData","endTime":"2016-02-12 10:06:35.522 UTC"},{"timeElapsedNanos":278503,"startTime":"2016-02-12 00:24:50.088 UTC","id":"org.springframework.boot.actuate.audit.AuditEventRepository.add","endTime":"2016-02-12 00:24:50.088 UTC"}],"producer":"com.ebee.app.web.rest.MetaGridResource.getGridQueryData"} }
{ "date": "2016-02-12 10:06:35", "level": "INFO ", "stats": {"slaTimes":[{"timeElapsedNanos":2803026,"startTime":"2016-02-12 10:06:35.519 UTC","id":"com.ebee.app.web.rest.MetaGridResource.getGridQueryData","endTime":"2016-02-12 10:06:35.522 UTC"}],"producer":"com.ebee.app.web.rest.MetaGridResource.getGridQueryData"} } 

i have these two json first one is successful but second one is throwing excepton 
Ruby exception occurred: undefined method `/' for #Hash:0x7f4ec4d0 {:level=>:error}

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.

Essentially `event['stats[slaTimes[timeElapsedNanos]]']` is returning a hash instead of a number, so you can't call method `/` on a Hash.
