### ISSUE TITLE
Unkonwn method scan

### ISSUE THREAD

**Issue by samuraiii** [logstash-plugins/logstash-filter-ruby#19]
Hi,
`event["hex"] = event["audit.a0"].scan(/(..)/).map{|a| a.first.to_i(16).chr}.join`
produces
`Ruby exception occurred: undefined method`scan' for nil:NilClass {:level=>:error}
`
How can I use such methods in ruby filter?
S

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.

For reference, the code you're using isn't protecting against events that don't contain a key "audit.a0", so the `event["audit.a0"]` returns nil, hence the error you're seeing.
