### ISSUE TITLE
Can't manipulate hash since Logstash 2.3

### ISSUE THREAD

**Issue by atschabu** [logstash-plugins/logstash-filter-ruby#21]
I recently tried upgrading to Logstash 2.3, and found an issue trying to manipulate a hash using the ruby filter. Using the following example:

    filter {
      ruby {
        code => "event['aHash'] = { 'key' => 'value' }"
      }
      ruby {
        code => "event['aHash']['key'] = 'newValue'"
      }
    }

the output is as expected with Logstash 2.2.3:

    "aHash" => {
        "key" => "newValue"
    },

but incorrect since Logstash 2.3:

    "aHash" => {
        "key" => "value"
    },

I'm executing Logstash using official docker image published to https://hub.docker.com/_/logstash/

**Comment by ph** [comment]
We shipped logstash 2.3 with a java implementation of the event class, but this change also mean that the event class doesn't support in place modification/mutation anymore (it returns copies), you have to change your code to the following.

```
filter {
  ruby {
    code => "event['aHash'] = { 'key' => 'value' }"
  }
  ruby {
    code => "t = event['aHash']; t['key'] = 'newValue'; event['aHash'] = t"
  }
}
```

the pure ruby example.
```ruby
t = event['aHash']
t['key'] = 'newValue'
event['aHash'] = t
```

Or you can use the **fieldref** syntax to change the value.
```
~/e/s/logstash-2.3.0 ❯❯❯ bin/logstash irb
irb(main):001:0> require "logstash/event"
=> true
irb(main):003:0> e = LogStash::Event.new({ "hola" => { "hello" => "PH" }})
=> 2016-03-31T18:43:17.482Z %{host} %{message}
irb(main):004:0> e["hola"]["hello"]
=> "PH"
irb(main):007:0> e["[hola][hello]"] = "Beatrice"
=> "Beatrice"
irb(main):008:0> e["hola"]["hello"]
=> "Beatrice"
irb(main):009:0>

```

**Comment by atschabu** [comment]
I see. This approach looks good to me, as it works for Logstash 2.2 and 2.3. And within the single threaded environment I'm currently trying this, I'm sure it is fine. 

Will this still work when using multiple threads, and multiple filters? Or is a single event guaranteed to be executed within a single Thread. Differently asked, is their any chance, that two ruby filters, doing this copy/manipulate/write hash approach to the same hash, might delete each others changes. I'm manipulating the '@ metadata' hash in multiple locations.

And one more question, is this documented somewhere? Because the few references I found for the ruby filter, use the approach I described in OP. For example here: https://www.elastic.co/blog/logstash-metadata

**Comment by ph** [comment]
> Will this still work when using multiple threads, and multiple filters? Or is a single event guaranteed to be executed within a single Thread. Differently asked, is their any chance, that two ruby filters, doing this copy/manipulate/write hash approach to the same hash, might delete each others changes. I'm manipulating the '@ metadata' hash in multiple locations.

You don't have to worry about it, our threading model doesn't allow multiple thread to change the same event. If you want to know more about the threading models of logstash I suggest you look at https://www.elastic.co/blog/logstash-2-2-0-and-2-1-2-released and https://www.elastic.co/blog/upgrade-guide-for-logstash-2-2

> And one more question, is this documented somewhere? Because the few references I found for the ruby filter, use the approach I described in OP. For example here: https://www.elastic.co/blog/logstash-metadata

I've wrote that post, I will check if I can update it. :)

I will make another port concerning the changes for the mutability targeted for the user of the ruby filter and plugins authors.

**Comment by ph** [comment]
Since it fixed your problem I will close that ticket.
