### ISSUE TITLE
Split issue

### ISSUE THREAD

**Issue by bighanraj** [logstash-plugins/logstash-filter-ruby#26]
Hi , i am getting below error when I use split method inside the ruby { } filter block.
Please help me out here.

Ruby exception occurred: undefined method `split' for nil:NilClass {:level=>:error}

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.

For reference, it just seems that the code you're using is calling split on something the event doesn't have, hence the split on nilclass exception.
