### ISSUE TITLE
Improve error handling on ruby filters that have not been rewritten to work with the new Java objects

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-filter-ruby#29]
With the switch to java events coming up in 5.0, a lot of users' existing ruby filters using the older style reference will break and LS will not run, eg.

event['fieldname'] = x
x = event['fieldname']

unless they are rewritten to use the java style get/set methods.

Currently, we throw an unintuitive error below:

```
[2016-10-07T11:54:18,580][ERROR][logstash.filters.ruby    ] Ruby exception occurred: undefined method `[]' for <content_of_message_here>
```

I will suggest improving the error message above with a more detailed description of the cause and include recommended changes (or perhaps a link to a documentation/blog post with examples of rewrites, etc..)

**Comment by jordansissel** [comment]
We can probably add a [] and []= methods back that only exist to error and show a helpful message to users.

**Comment by acchen97** [comment]
We can use verbiage similar to:

"Direct event field references (i.e. event['field']) have been disabled in favor of using event get and set methods (e.g. event.get('field')). Please consult the Logstash 5.0 breaking changes documentation for more details."

**Comment by ppf2** [comment]
Thanks @acchen97 any chance of getting this in before the 5.0 GA? @pickypg

**Comment by suyograo** [comment]
@ppf2 I don't think this is a blocker so it will have to be after GA.

**Comment by suyograo** [comment]
we can get this for 5.0.1, however.

**Comment by guyboertje** [comment]
Fixed in LS PR https://github.com/elastic/logstash/pull/6045 merged.
