### ISSUE TITLE
LoadError: no such file to load -- dbi

### ISSUE THREAD

**Issue by chengwei-li** [logstash-plugins/logstash-filter-ruby#40]
## In logstash-filter-ruby, I want to require ‘dbi‘ module to access mysql, the specific configuration is as follows：
input{ //code}
filter{
	mutate{
		split =>["message","|"]
	}
	ruby {
	 init => ["require 'dbi'"]
         code => "//other code..."
}
## After running logstash the following exception occurred  ：
[root@node02 logstash]# bin/logstash -f /etc/logstash/conf.d/ruby-mysql.conf 
Sending Logstash's logs to /var/log/logstash which is now configured via log4j2.properties
LoadError: no such file to load -- dbi
           require at org/jruby/RubyKernel.java:1040
           require at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
          register at (ruby filter init):1
              eval at org/jruby/RubyKernel.java:1079
          register at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-3.1.2/lib/logstash/filters/ruby.rb:58
          register at /usr/share/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
   register_plugin at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:290
  register_plugins at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301
              each at org/jruby/RubyArray.java:1613
  register_plugins at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301
     start_workers at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:311
               run at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:235
    start_pipeline at /usr/share/logstash/logstash-core/lib/logstash/agent.rb:408

In Centos env，I have installed：
sudo gem install dbi
sudo gem install mysql
sudo gem install dbd-mysql

I would like to know in the logstash-filter-ruby , whether it can require dbi module, if so, how to operate.
Thank you！

- Version:logstash-5.6.5
- Operating System:centos7

**Comment by jsvd** [comment]
the ruby filter isn't made to require dependencies that don't ship with logstash, by doing gem install you only install the gems of the system's ruby, not what logstash uses.

To have a filter use custom code and new dependencies you need a custom filter. Here is the guide: https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html
