### ISSUE TITLE
Filter never "succeeds" when using a script file

### ISSUE THREAD

**Issue by darefilz** [logstash-plugins/logstash-filter-ruby#47]
When the `path` option is used to execute a ruby script file, the filter does not succeed, so options like `add_field`, `remove_tag`, etc. are never applied.

---
- Logstash version: 5.6
- Plugin version: 3.1.4
- Operating System: Linux
#### Config File
```
ruby {
  path => "test.rb"
  add_field => { "test_field" => "success" }
}
```
#### Ruby file ("test.rb")
```ruby
def filter(event)
  return [event]
end
```
#### Steps to Reproduce
1. Generate a logstash event
2. Apply the given ruby filter
3. Maybe dump it to stdout

#### Expectation
The event contains the field "test_field"
#### Observation
"test_field" is missing

In contrast, if the `code` option of the ruby filter is used (instead of `path`) the resulting event does contain the expected field.

**Comment by jsvd** [comment]
This has been fixed in 3.1.5: https://github.com/logstash-plugins/logstash-filter-ruby/blob/master/CHANGELOG.md#315
