### ISSUE TITLE
Release with option 'tag_with_exception_message'

### ISSUE THREAD

**Issue by peacand** [logstash-plugins/logstash-filter-ruby#57]
Hi,

I've just seen in the current master branch that there is a configuration option for this filter 'tag_with_exception_message' which is pretty cool. It was added almost 2 years ago now but there was no new release since, so this option is not available to use.

Would it be possible to release a new version with this simple configuration option ?

**Comment by kaisecheng** [comment]
Hi @peacand a new version `3.1.6` is released recently. Thanks for reporting the issue
