### ISSUE TITLE
Logstash uses ruby filter plugin to parse events incorrectly,This is a random event.

### ISSUE THREAD

**Issue by johncai0** [logstash-plugins/logstash-filter-ruby#58]
Use the ruby filter plugin to split the event message, but the split result is inconsistent with the message.

sys version: CentOS Linux release 7.4.1708 (Core)
logstash version: logstash-6.8.0
java version "1.8.0_191"(HotSpot)

logstash config:
`
input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "app" => "%{[fields][app]}"}
    add_field => { "serverip" => "%{[fields][ip]}"}
  }
    ruby {
    code => "
    if event.get('app') == 'nginx'
      NG_ARR = event.get('message').split(/\"/)
      NG_ARR_LEN = NG_ARR.length
     .....
    elsif event.get('app') == 'springBoot'
      CA_ARR = event.get('message').split(/ /)
      CA_ARR_LEN = CA_ARR.length
      ......
    else
      AP_ARR = event.get('message').split(/ /)
      AP_ARR_LEN = AP_ARR.length
      if AP_ARR_LEN >=  7
        event.set('[metadata][tsprefix]', event.get('timestamp').to_i.to_s(16))
        dt=Time.strptime(AP_ARR[0]+' '+AP_ARR[1], '%Y-%m-%d %H:%M:%S.%N')
        event.set('log_time', dt.strftime('%Y-%m-%d %H:%M:%S.%3N'))
        event.set('log_date', dt.strftime('%Y-%m-%d'))
        event.set('log_timestamp',(dt.to_f*1000).to_i)
        **AP_ARR[2].blank? ? event.set('level', '') : event.set('level', AP_ARR[2])**
        AP_ARR[3].blank? ? event.set('pid', '') : event.set('pid', AP_ARR[3])
        AP_ARR[4].blank? || AP_ARR[4] == '-' ? event.set('ptx_id', '') : event.set('ptx_id', AP_ARR[4])
        AP_ARR[5].blank? || AP_ARR[5] == '-' ? event.set('pspan_id', '') : event.set('pspan_id', AP_ARR[5])
        if AP_ARR[6] == 'xxl-rpc,'
          AP_ARR[7].blank? ? event.set('thread_name', '') : event.set('thread_name', AP_ARR[7])
          AP_ARR[8].blank? ? event.set('logger', '') : event.set('logger', AP_ARR[8])
        else
          AP_ARR[6].blank? ? event.set('thread_name', '') : event.set('thread_name', AP_ARR[6])
          AP_ARR[7].blank? ? event.set('logger', '') : event.set('logger', AP_ARR[7])
        end
        event.remove('path') if event.get('path')
        event.set('path',event.get('source'))
      else
        event.set('[tags]', '_ruby_1_parse_failure')
      end
    end
    "
  }

}

output {
  if [tags] {
      file {
          codec => "rubydebug"
          path => "/var/log/logstash/failure-%{+YYYY-MM}.log"
    }
  } else if [app] == 'nginx' {
elasticsearch {
          ....
      }
  } else if [app] == 'springBoot' {
elasticsearch {
          ....
      }
} else {
elasticsearch {
          ....
      }
  }
}
`
The above is the configuration file. If [app]=='other' go to the 'else' branch of "ruby code" in "filter", the following situation will occur

`{
        "_index" : "other_2020-09-08",
        "_type" : "other",
        "_id" : "UmypbnQBUPPjac8YIgbf",
        "_score" : 0.0,
        "_source" : {
          "log_timestamp" : 1599584410291,
          "level" : **"INFO"**,
          "logger" : "org.apache.zookeeper.ClientCnxn",
          "app" : "other",
          "@timestamp" : "2020-09-08T17:00:16.805Z",
          "log_date" : "2020-09-09",
          "pid" : "19731",
          "serverip" : "127.0.0.1",
          "log_time" : "2020-09-09 01:00:10.291",
          "@version" : "1",
          "thread_name" : "main-SendThread(172.20.7.135:2181)",
          "pspan_id" : "",
          "path" : "/data/apps/clue-service/logs/info.log",
          "ptx_id" : "",
          "message" : "2020-09-09 01:00:10.288 **WARN** 19731 - - main-SendThread(172.20.7.135:2181) org.apache.zookeeper.ClientCnxn 957 SASL configuration failed
}`

The value of level is separated by spaces to get the element whose subscript is 2. It should be WARN, but here is INFO,this is a random event

logstash config:
`
# grep -Ev '^$|#' logstash.yml
**pipeline.workers: 2**
config.reload.automatic: true
config.reload.interval: 3s
path.logs: /data/logstash-6.8.0/logs
xpack.monitoring.enabled: false
`

**Comment by johncai0** [comment]
Is it related to the parallelism of pipeline.workers=2

**Comment by yaauie** [comment]
In Ruby, "variables" with capital letters are _constants_, which are shared state.

The issue you're hitting is that multiple events can be processed by this plugin _simultaneously_, and since your code is defined in such a way that it is mutating shared state, we have no guarantees the shared mutable state was last modified by the current thread.

The solution is to use local variables (which in ruby, begin with a lower-case letter or an underscore).
