### ISSUE TITLE
yield doesn't work

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-ruby#6]
Filters can yield new events if the current event should cause extra events to be created at this point in the pipeline (clone and split do this, iirc).

I think yield fails in the ruby filter: `{"exception"=>#<LocalJumpError: yield called out of block>,`

Example: `ruby { code => 'yield event' }`

**Comment by wiibaa** [comment]
Correct me if I'm wrong, but yield inside a lambda will never work.
Therefore we must explicitly pass the block and document how to use it
Before proposing a PR, can you please comment if this approach would be correct

````
@@ -27,15 +27,15 @@ class LogStash::Filters::Ruby < LogStash::Filters::Base
   def register
     # TODO(sissel): Compile the ruby code
     eval(@init, binding, "(ruby filter init)") if @init
-    eval("@codeblock = lambda { |event| #{@code} }", binding, "(ruby filter code)")
+    eval("@codeblock = lambda { |event, &new_event_block| #{@code} }", binding, "(ruby filter code)")
   end # def register

   public
-  def filter(event)
+  def filter(event,&block)
     return unless filter?(event)

     begin
-      @codeblock.call(event)
+      @codeblock.call(event,&block)
       filter_matched(event)
     rescue Exception => e
       @logger.error("Ruby exception occurred: #{e}")
````

proposed test (making a simple copycat)
````
describe "made a copycat clone of the event" do
    config <<-CONFIG
      filter {
        ruby {
          code => "new_event_block.call(event)"
        }
      }
    CONFIG

    sample("message" => "hello world", "mydate" => "2014-09-23T00:00:00-0800") do
      expect(subject).to be_a Array
      expect(subject[0]).to eq(subject[1])
    end
  end
````

**Comment by webwurst** [comment]
I am getting this error. Any news on this? :)

**Comment by jordansissel** [comment]
The workaround for now is to write your own filter.

**Comment by webwurst** [comment]
Ok thx! Will try that.

**Comment by jsvd** [comment]
while yield doesn't work, there's an alternative solution https://github.com/logstash-plugins/logstash-filter-ruby/pull/10/files.
